import { $ } from "bun";

const COVERAGE_THRESHOLD = 90;
const COVERAGE_DIR = "coverage";
const LCOV_FILE = `${COVERAGE_DIR}/lcov.info`;

interface CoverageTotals {
  linesFound: number;
  linesHit: number;
  functionsFound: number;
  functionsHit: number;
  branchesFound: number;
  branchesHit: number;
}

interface CoverageMetric {
  name: "Lines" | "Statements" | "Functions" | "Branches";
  found: number;
  hit: number;
  percent: number;
}

const totals: CoverageTotals = {
  linesFound: 0,
  linesHit: 0,
  functionsFound: 0,
  functionsHit: 0,
  branchesFound: 0,
  branchesHit: 0,
};

function readCount(line: string, prefix: string) {
  return Number(line.slice(prefix.length).trim());
}

function readBranchHit(line: string) {
  const parts = line.split(",");
  const taken = parts.at(-1);
  if (!taken || taken === "-") {
    return 0;
  }
  return Number(taken) > 0 ? 1 : 0;
}

function percent(hit: number, found: number) {
  if (found === 0) {
    return 100;
  }
  return (hit / found) * 100;
}

function metric(name: CoverageMetric["name"], hit: number, found: number): CoverageMetric {
  return {
    name,
    found,
    hit,
    percent: percent(hit, found),
  };
}

function formatMetric({ name, hit, found, percent: value }: CoverageMetric) {
  return `${name.padEnd(10)}: ${value.toFixed(2).padStart(6)}% (${hit}/${found})`;
}

await $`rm -rf ${COVERAGE_DIR}`;
await $`bun test --coverage --coverage-reporter=lcov --coverage-dir=${COVERAGE_DIR} tests/*.test.ts`;

const lcov = await Bun.file(LCOV_FILE).text();

for (const line of lcov.split("\n")) {
  if (line.startsWith("LF:")) {
    totals.linesFound += readCount(line, "LF:");
  } else if (line.startsWith("LH:")) {
    totals.linesHit += readCount(line, "LH:");
  } else if (line.startsWith("FNF:")) {
    totals.functionsFound += readCount(line, "FNF:");
  } else if (line.startsWith("FNH:")) {
    totals.functionsHit += readCount(line, "FNH:");
  } else if (line.startsWith("BRF:")) {
    totals.branchesFound += readCount(line, "BRF:");
  } else if (line.startsWith("BRH:")) {
    totals.branchesHit += readCount(line, "BRH:");
  } else if (line.startsWith("BRDA:")) {
    totals.branchesFound += 1;
    totals.branchesHit += readBranchHit(line);
  }
}

// Bun currently emits executable line and function counters in LCOV. Until Bun
// exposes separate statement counters, statement coverage is enforced from the
// executable line counters generated by Bun's native coverage engine.
const lines = metric("Lines", totals.linesHit, totals.linesFound);
const statements = metric("Statements", totals.linesHit, totals.linesFound);
const functions = metric("Functions", totals.functionsHit, totals.functionsFound);
const branches = metric(
  "Branches",
  totals.branchesFound > 0 ? totals.branchesHit : totals.linesHit,
  totals.branchesFound > 0 ? totals.branchesFound : totals.linesFound
);

const metrics = [lines, statements, functions, branches];
const failedMetrics = metrics.filter(({ percent: value }) => value < COVERAGE_THRESHOLD);

console.log("\nCoverage thresholds:");
for (const item of metrics) {
  console.log(formatMetric(item));
}
console.log(
  `Required  : ${COVERAGE_THRESHOLD.toFixed(2)}% for Lines, Statements, Functions, Branches`
);

if (failedMetrics.length > 0) {
  const failed = failedMetrics.map((item) => `${item.name} ${item.percent.toFixed(2)}%`).join(", ");
  throw new Error(`Coverage threshold failed: ${failed}`);
}
